name: search_player
description: O SearchPlayer é uma plataforma web onde os fãs de futebol,
  jornalistas e curiosos podem consultar e extrair rapidamente informações
  de jogadores do esporte, em todo o mundo. Além de disponibilizar informações
  dos players, a plataforma disponibiliza vídeos do youtube referente ao atleta
  consultado diretamente na plataforma.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  splashscreen: ^1.2.0
  toast: ^0.1.5
dev_dependencies:

  flutter_test:
    sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "lib/img/icon.png"

flutter:

  assets:
    - lib/img/logo_search.png
    - lib/img/icon.png
  uses-material-design: true

